# Generated by Django 6.1.1 on 2026-09-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_user_post_created_at_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, choices=[('investment', 'Investment'), ('personal-finance', 'Personal Finance'), ('real-estate', 'Real Estate'), ('cryptocurrency', 'Cryptocurrency'), ('entrepreneurship', 'Entrepreneurship'), ('technology', 'Technology'), ('software-development', 'Software Development'), ('artificial-intelligence', 'Artificial Intelligence'), ('cybersecurity', 'Cybersecurity'), ('health-wellness', 'Health & Wellness'), ('fitness', 'Fitness'), ('diet-nutrition', 'Diet & Nutrition'), ('mental-health', 'Mental Health'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('food-cooking', 'Food & Cooking'), ('productivity', 'Productivity'), ('career', 'Career'), ('marketing', 'Marketing'), ('design', 'Design'), ('education', 'Education'), ('parenting', 'Parenting'), ('sustainability', 'Sustainability'), ('entertainment', 'Entertainment'), ('books-literature', 'Books & Literature')], to='blog.tag'),
        ),
    ]
