# Generated by Django 6.1.1 on 2026-09-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0009_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_index', models.IntegerField()),
                ('sent_index', models.IntegerField()),
                ('text', models.TextField()),
                ('section', models.CharField(blank=True, max_length=200)),
                ('is_code', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='blog.post')),
            ],
            options={
                'ordering': ['para_index', 'sent_index'],
                'constraints': [models.UniqueConstraint(fields=('post', 'para_index', 'sent_index'), name='uniq_sentence_address')],
            },
        ),
    ]
